
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::112108975903:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-oY6Z8l1iYvJp
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - userarn: arn:aws:iam::112108975903:user/ramesh
      groups:
      - roboshop-trainee

kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-26T04:22:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1113"
  uid: 305d001c-02e8-41d2-9510-16cdd9cddd60
