apiVersion: apps/v1 
kind: Deployment
metadata:
  name: pod-demo
  namespace: roboshop-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1 
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80